### ISSUE TITLE
directory misspelling

### ISSUE THREAD

**Issue by phil333** [oKermorgant/calibration_gazebo#1]
When using the landmark.launch, it points to "$(find slider_publisher)/example/Twist.yaml".
The folder **example** does not exist, only the folder **examples** can be found

**Comment by oKermorgant** [comment]
Hi, 

Thanks for the remark, I have corrected the typo and some Python3 compatibility in commit #https://github.com/oKermorgant/calibration_gazebo/commit/4fdd7fb6aee63573278a65e386289a7ba38310a4
