### ISSUE TITLE
Resource not found: slider_publisher

### ISSUE THREAD

**Issue by kanishkanarch** [oKermorgant/calibration_gazebo#2]
Launching `landmark.launch` results in the error which says that `slider_publisher is not found`.
![image](https://user-images.githubusercontent.com/52484751/107409707-76c39c80-6b32-11eb-908f-b060a1921e1a.png)
I could not find much on the internet on how to download this package in ROS. Please guide me in this.

**Comment by oKermorgant** [comment]
Hi, 
Thanks for your interest. The slider_publisher package can be found here: https://github.com/oKermorgant/slider_publisher

**Comment by kanishkanarch** [comment]
Thank you for referring me the correct package. 
I can now move the checkerboard using the spawned slider windows. 
I am using Camera Calibration package of ROS to calibrate this simulator's camera, but I'm not sure about what should go into the `camera:=/`argument of the calibration command.
The calibration command given on ROS Wiki is `rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.108 image:=/camera/image_raw camera:=/camera`, and I know that my image argument should be like `image:=/ardrone/front/image_raw`, but I don't know what should go into the second argument, `camera:=/camera`

Please guide me in this naive problem of mine, I'm a beginner in ROS. Thanks


Update: For this argument, I used `camera:=/ardrone/front` and it is working now. 
Thanks for all your help, @oKermorgant , if you allow, can I close this issue?

**Comment by oKermorgant** [comment]
Hi, glad you could solve this issue. I'll close it.
