### ISSUE TITLE
Error while launching landmark.launch file

### ISSUE THREAD

**Issue by alphaanyms05** [oKermorgant/calibration_gazebo#3]
I am facing issues while launching the landmark node.
I am trying to launch the landmark.launch file, but I am getting an error:

> Resource not found: slider_publisher
> ROS path [0]=/opt/ros/noetic/share/ros
> ROS path [1]=/home/alpha/catkin_ws/src/calibration_gazebo
> ROS path [2]=/opt/ros/noetic/share
> The traceback for the exception was written to the log file

Can anyone help me with this? What is the slider_publisher node?

**Comment by alphaanyms05** [comment]
Can you help me @oKermorgant ?

**Comment by oKermorgant** [comment]
Hi, you can install this package from the debian repositories (`ros-noetic-slider-publisher`) or download from source here: https://github.com/oKermorgant/slider_publisher
