### ISSUE TITLE
Initial pose of checkerboard

### ISSUE THREAD

**Issue by seqwalt** [oKermorgant/calibration_gazebo#4]
Hi Dr.Kermorgant @oKermorgant, thanks for the nice repo! If my camera is not recognized for landmark positioning, is it possible to manually enter the desired start pose of the landmark (so I don't have to use the slider gui to get the checker board in the right starting spot). In other words, how do I spawn the landmark at a desired position and orientation?

**Comment by oKermorgant** [comment]
Hi

I guess the workaround is to passing the initial pose as parameters in move_landmark.py and set launch arguments accordingly.

**Comment by seqwalt** [comment]
Ok, thanks!
